liip_imagine:

  driver: "gd"

  resolvers:
    default:
      web_path:
        web_root: "%kernel.project_dir%/public"
        cache_prefix: media/cache

  loaders:
    default:
      filesystem:
        data_root: "%kernel.project_dir%/public/images/properties"
        bundle_resources:
          enabled: true

  data_loader: default
  cache: default


  filter_sets:
    thumb:
      jpeg_quality: 75
      filters:
        thumbnail: {size: [320, 180], mode: outbound}
    medium:
      jpeg_quality: 75
      filters:
        thumbnail: {size: [800, 530], mode: outbound}